# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsonstt', '0006_custid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hkword', models.CharField(max_length=200)),
                ('hkdisp', models.CharField(max_length=200)),
                ('hksoundslike', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
