# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watsonstt', '0007_auto_20170226_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hksoundslike', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tempword',
            name='hksoundslike',
        ),
        migrations.AddField(
            model_name='tempsound',
            name='hkwordkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsonstt.TempWord'),
        ),
    ]
