# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsonstt', '0003_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hkword', models.CharField(max_length=200)),
                ('hkdisp', models.CharField(max_length=200)),
            ],
        ),
    ]
