# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watsonstt', '0004_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hksoundslike', models.CharField(max_length=200)),
                ('hkwordkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsonstt.Word')),
            ],
        ),
    ]
